version: "3.8"

services:
  alpine:
    container_name: alpine
    build:
      context: .
      dockerfile: ./symfony_config/Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./symfony_config/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./symfony_project:/var/www/html
    networks:
      - dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: db
    image: "mariadb:10.3"
    restart: on-failure
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: data
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    networks:
      - dev

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: on-failure
    depends_on:
      - db
    ports:
      - "7777:80"
    environment:
      PMA_HOST: db
    networks:
      - dev
networks:
  dev:

volumes:
  db-data:
